name: Label Audit
on: [push]
jobs:
  labels:
    runs-on: SalesforceFoundation-ubuntu
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Determine Python Version
        id: python-version
        run: |
          echo "::set-output name=ver::$(python --version)"
      - uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-${{ steps.python-version.outputs.ver }}-${{ hashFiles('requirements.txt') }}
      - name: Install Packages
        run: |
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
      - name: Label Audits
        run: |
          venv/bin/python scripts/label_audit.py
